name: poke_book
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.1
  flutter_native_splash: ^2.3.2
  flutter_onboard: ^2.0.0
  flutter_tabler_icons: ^1.2.0
  go_router: ^10.1.0
  google_fonts: ^5.1.0
  firebase_crashlytics: ^3.3.5
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  flutter_slidable: ^3.0.0
  intl: any
  path_provider: ^2.1.0
  flutter_html: ^3.0.0-beta.2
  top_modal_sheet: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  icons_launcher: ^2.1.3
  launcher_name: ^1.0.1
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/docs/
    - assets/logos/
    - assets/icons/
    - assets/images/
    - assets/images/regions/
    - assets/images/pokemons/
    - assets/images/types/

flutter_native_splash:
  color: "#000029"
  image: assets/images/splash.png
  android: false
  ios: true
  web: false

icons_launcher:
  image_path: "assets/logos/logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

launcher_name:
  default: "PokeBook"