// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh4Y4onPcSRMX8yD8ZNTUep6aTx2NNxX4',
    appId: '1:591557568280:web:eeae5b6c3a029e1ce4206d',
    messagingSenderId: '591557568280',
    projectId: 'pokebook-slymstudio-com',
    authDomain: 'pokebook-slymstudio-com.firebaseapp.com',
    storageBucket: 'pokebook-slymstudio-com.appspot.com',
    measurementId: 'G-1VBLJTT626',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBArRPh10uoO8ieRTUqjjwhU-3BNTebUkQ',
    appId: '1:591557568280:android:0aa944ddbda36a54e4206d',
    messagingSenderId: '591557568280',
    projectId: 'pokebook-slymstudio-com',
    storageBucket: 'pokebook-slymstudio-com.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5ZdVgCQiemelc_a6d5D-y2XxM8hdWOhk',
    appId: '1:591557568280:ios:09b8585e3fa925f4e4206d',
    messagingSenderId: '591557568280',
    projectId: 'pokebook-slymstudio-com',
    storageBucket: 'pokebook-slymstudio-com.appspot.com',
    iosClientId: '591557568280-9ipnurj4jibg3brgv1skub5o8jh47ibg.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokeBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5ZdVgCQiemelc_a6d5D-y2XxM8hdWOhk',
    appId: '1:591557568280:ios:0ca03566553b357be4206d',
    messagingSenderId: '591557568280',
    projectId: 'pokebook-slymstudio-com',
    storageBucket: 'pokebook-slymstudio-com.appspot.com',
    iosClientId: '591557568280-bue6eq416vidrcudpp7g953uu53qbl35.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokeBook.RunnerTests',
  );
}
